Add bookings
Scutc/java-shareit pull request #3
Opened 2022-12-26 14:07 UTC by Scutc

Привет! Очень вязкое ТЗ получилось, долго возился с тестами постман, сделаешь одно, поломается то, что раньше работает :) Отправляю работу на ревью с тех. долгом - нужно будет дописать интеграционные тесты, сделаю это на следующую итерацию вместе с исправлениям после ревью.

2022-12-27 18:18 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа, давай чутка доработаем:

1) Вопрос, а для чего нужен файл shareit.mv.db?
2) @JsonFormat не заметил что используем
3) Напоминание для названий методов:
- get - используем там где возвращаем или объект или исключение
- find - где или объект или null

В остальном в целом очень неплохо

2022-12-27 18:18 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(name = "user_id", nullable = false)
Тоже уточню почему user_id а не просто id

2022-12-27 18:18 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        User userForDelete = userRepository.getUserById(userId);
Давай тут сделаем сразу метод в сервисе получения человека или выброс исключения (без маппинга) и тогда тут не будем дублировать проверку

2022-12-27 18:18 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getBookingByOwner(ownerId, state);
Лучше всю "неопределенность" решать на уровне контролеров и в сервис передавать уже или ALL или то что пользователь передал

2022-12-27 18:18 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private Long id;
Тут аналогичный вопрос почему comment_id в бд а не id

2022-12-27 20:22 UTC, Scutc commented on src/main/resources/schema.sql
> +    email    VARCHAR(60) NOT NULL,
Поправил, спасибо!

2022-12-27 20:23 UTC, Scutc commented on pom.xml
> +			<artifactId>jackson-datatype-joda</artifactId>
Пытался одну задачку с помощью JsonFormat решить, потом пошел другим путем, зависимость не убрал. Сейчас поправил

2022-12-27 20:52 UTC, Scutc commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Column(name = "booking_id", nullable = false)
Так видел художник :) поменял

2022-12-27 21:02 UTC, Scutc commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne(fetch = FetchType.EAGER)
Да, последствия понятны. Хотел использовать LAZY сначала, но возникала ошибка сериализации, которую я не нашел как быстро победить. Дергать вручную поля объекта не хотелось.

2022-12-27 21:04 UTC, Scutc commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @Column(name = "user_id", nullable = false)
поправил

2022-12-27 21:04 UTC, Scutc commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +    private Long id;
поправил

2022-12-28 06:23 UTC, Scutc commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingRepository.findBookingById(bookingId, userId);
Я сделал сначала, но стали падать некоторые тесты, т.к. в методах апдейта и получения букинга ожидаются разные коды ошибок. В getBookingById 404, а в updateBooking 400 или 500. Поэтому вернул в исходное состояние

2022-12-28 06:29 UTC, Scutc commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +        User userForDelete = userRepository.getUserById(userId);
переделал на try catch без дополнительной проверки

2022-12-28 06:37 UTC, Scutc commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getBookingByOwner(ownerId, state);
переделал

2022-12-28 08:55 UTC, Scutc commented
Привет! Вроде все учел :)

2022-12-28 18:19 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки и вроде все хорошо поэтому - зачет!

2022-12-29 07:14 UTC, merged