Add item requests
Scutc/java-shareit pull request #4
Opened 2023-01-05 12:00 UTC by Scutc

Привет! С Новым годом! =) 
По проекту ТЗ реализовал, по тестам сделал все виды тестов, чтобы потренироваться, но конечно без фанатизма, и так очень утомился их писать и заскучал =) Надеюсь не будешь сильно заставлять меня дописывать большое кол-во тестов ))

2023-01-07 19:50 UTC, krylov-sergey-sergeevich requested changes
Привет, с новым годом =) В целом неплохой pr, но кое что улучшим

_p.s тут работает анекдот написал разраб 50 строк кода и отдал на ревью ему нашли 15 ошибок, написал разраб 500 строк кода и отдал на ревью ему сказали "нормально вливай"_

Возвращаясь к нашему проекту =) Бизнес код хороший, уже видно что навык наработан по тестам есть вопросик
1) Почитай про verify в Mockito полезная штука
2) В тестах очень часто вижу упущены модификаторы доступа для переменных и методов, надо как то единообразно систематизировать и еще что в некоторых тестах есть переменные которые используются в 2-3 и более тестах т.е. они определены на уровне класса и их используем, это прям опасно тк если когда нибудь тесты запараллелены будут это потом может аукнуться плюс так можно случайно поймать какой то side effect так называемый с другого теста. Поэтому по возможности давай улучшим это где совсем критично, но в целом еще чутка и будет зачет.

2023-01-07 19:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/utility/PaginationConverter.java
> +@Data
Зачем data аннотация?

2023-01-07 19:50 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/practicum/shareit/booking/BookingDtoResponseJsonTest.java
> +@JsonTest
Интересная аннотация

2023-01-07 19:50 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getBookingByOwner(ownerId, state, from, size);
Я бы рекомендовал бы создать сущность объединяющую from и size и гонять ее по уровням, а не передавать везде как два параметра тк уровней вложенности может быть много и везде этот дубляж ну такое

Но это не обязательно

2023-01-11 14:25 UTC, Scutc commented on pom.xml
> +            <groupId>junit</groupId>
указал. Но помню твои комментарии к групповому проекту, там ты просил убрал лишние указания версий, поэтому я немного запутался :) Нужно ли все-таки специфицировать версии или нет.

2023-01-11 14:26 UTC, Scutc commented on src/test/java/ru/practicum/shareit/booking/BookingDtoResponseJsonTest.java
> +@JsonTest
В материалах спринта давали :)

2023-01-11 14:27 UTC, Scutc commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getBookingByOwner(ownerId, state, from, size);
Оставлю так тогда пока, устал от ТЗ ))

2023-01-11 14:32 UTC, Scutc commented on src/main/java/ru/practicum/shareit/utility/PaginationConverter.java
> +@Data
В какой-то из версий видимо ее использовал. Сейчас убрал

2023-01-11 15:25 UTC, Scutc commented
Привет! Учел все обязательное, опциональное не все :) Добавил парочку реализаций Mockito.verify чтобы попрактиковаться

2023-01-12 20:50 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <groupId>junit</groupId>
Это работает на интуитивном уровне, в своей жизни тебе придется хлебнуть страданий с этими версиями библиотек и их конфликтами поэтому тут сложно дать "решение на все случаи жизни", но вот сейчас лично меня смутило что это объявлен junit а не unit5 тк мне кажется что junit5 по другому определяют (вообще и без этой зависимости вроде как должно работать тк spring-starter-test должен в себя включать, но вдруг)

2023-01-12 20:52 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, видно что устал и кхех делается самое обязательное, но понимаю - зачет,  год рабочий начинается со скрипом)

Удачи и терпения со следующими дз =)

2023-01-12 20:52 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <groupId>junit</groupId>
Емае я писал писал, а потом увидел что это junit 4 в коде определен

2023-01-13 07:20 UTC, merged